---
- name: "Update the hosts in the inventory"
  hosts: targets
  become: true
  tasks:
    - name: DNF update the system
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == "dnf"

    - name: Update Debian (based) systems
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
      when: ansible_pkg_mgr == "apt"

    - name: Yum update the system
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == "yum"

    - name: Reboot the machine
      ansible.builtin.reboot:
        reboot_timeout: 360
