---
- name: "Enable the needed services"
  hosts: targets
  become: true
  tasks:
    - name: Enable nginx and cockpit and start the services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - nginx
        - cockpit
        - cockpit.socket
