- name: Enabling UFW, denying all traffic by default
  community.general.ufw:
    state: enabled
    policy: deny

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Allow defined firewall rules
  community.general.ufw:
    rule: "{{ item.policy }}"
    port: "{{ item.port }}"
  loop: "{{ firewall_rules }}"

- name: Restart UFW
  community.general.ufw:
    state: reloaded