---
- name: Running the playbook on the following OS
  debug:
    msg:
      - "{{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- name: "Run all playbooks for {{ ansible_distribution }}"
  include_tasks: ./total.yml
  when: ansible_distribution in ['Debian']