---
- name: Print linux distribution and version
  hosts: targets
  become: true
  tasks:
    - name: Running the playbook on the following OS
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- name: "Run all playbooks for {{ ansible_distribution }}"
  ansible.builtin.import_playbook: playbooks/total.yml
  when: ansible_distribution in ['Debian']
