---
- name: Print linux distribution and version
  hosts: targets
  tasks:
    - name: Running the playbook on the following OS
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- name: Run the initial playbooks
  ansible.builtin.import_playbook: playbooks/total.yml
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Rocky', 'Alma']
