---
- name: "Set the firewall rules"
  hosts: targets
  become: true
  tasks:
    - name: Enabling UFW, allowing all traffic
      community.general.ufw:
        state: enabled
        policy: deny

    - name: Set logging
      community.general.ufw:
        logging: 'on'

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: '22'

    - name: Allow HTTP
      community.general.ufw:
        rule: allow
        port: '80'

    - name: Allow HTTPS
      community.general.ufw:
        rule: allow
        port: '443'

    - name: Restart UFW
      community.general.ufw:
        state: reloaded
