---
- name: "Install packages on all server and setup basic configuration"
  hosts: targets
  become: true
  tasks:
    - name: APT update the system
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: Ensure packages are installed
      ansible.builtin.apt:
        name:
          - ufw
          - apt-transport-https
          - ca-certificates
          - nginx
          - zsh
          - curl
          - lsb-release
          - wget
          - gnupg
          - gpg
          - jq
        state: present
